### ISSUE TITLE
无法正常解析1.13.2的json文件

### ISSUE THREAD

**Issue by ChinaNuke** [to2mbn/JMCCC#30]
`Caused by: org.to2mbn.jmccc.internal.org.json.JSONException: JSONObject["extract"] not found.`

**Comment by xfl03** [comment]
请确认1.14.3和1.12.2的可用性，谢谢

**Comment by ChinaNuke** [comment]
1.14.3和上面一样的问题。
1.12.2可以启动，但是在MOJANG那个加载窗口待一会儿窗口就没了。

日志输出：

`[19:43:15] [Client thread/INFO]: Setting user: ChinaNuke
[19:43:19] [Client thread/INFO]: LWJGL Version: 2.9.4
[19:43:19] [Client thread/INFO]: Reloading ResourceManager: Default
[19:43:27] [Sound Library Loader/INFO]: Starting up SoundSystem...
[19:43:28] [Thread-2/INFO]: Initializing LWJGL OpenAL
[19:43:28] [Thread-2/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/C:/Users/Peng/eclipse-workspace/MinecraftLauncher/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[19:43:28] [Thread-2/INFO]: OpenAL initialized.
[19:43:28] [Sound Library Loader/INFO]: Sound engine started
[19:43:37] [Client thread/INFO]: Created: 1024x512 textures-atlas`

Minecraft Crash Report:

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2019-07-01 19:43
Description: Initializing game

java.lang.NoClassDefFoundError: com/mojang/text2speech/Narrator
	at biv.<init>(SourceFile:15)
	at biv.<clinit>(SourceFile:14)
	at biq.<init>(SourceFile:127)
	at bib.aq(SourceFile:557)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
Caused by: java.lang.ClassNotFoundException: com.mojang.text2speech.Narrator
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:


-- Head --
Thread: Client thread
Stacktrace:
	at biv.<init>(SourceFile:15)
	at biv.<clinit>(SourceFile:14)
	at biq.<init>(SourceFile:127)
	at bib.aq(SourceFile:557)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.3, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 24560640 bytes (23 MB) / 139460608 bytes (133 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 1 total; -Xmx1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 615 GL version 4.5.0 - Build 23.20.16.4974, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Probably not. Jar signature remains and client brand is untouched.
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz

**Comment by xfl03** [comment]
> Java Version: 11.0.3, Oracle Corporation

请考虑降级Java

**Comment by ChinaNuke** [comment]
官方启动器下的文件和HMCL下的文件都试过了，一样的问题，是我用的版本不对吗？
![image](https://user-images.githubusercontent.com/17084130/60750711-378cab80-9fdf-11e9-9bfd-214243a7e6f8.png)

**Comment by xfl03** [comment]
https://csl.littleservice.cn/libraries/org/to2mbn/jmccc/2.5-SNAPSHOT/jmccc-2.5-SNAPSHOT.jar

**Comment by ChinaNuke** [comment]
这就成了……原来是因为这个，谢谢你了
