### ISSUE TITLE
1.15.2Fabric-loader启动出问题

### ISSUE THREAD

**Issue by 1871847400** [to2mbn/JMCCC#32]
纯净版没有问题，Fabric启动会缺失资源文件，声音图标语言文件都没有。

[15:18:58] [main/ERROR]: Couldn't set icon
java.io.FileNotFoundException: icons/icon_16x16.png
	at net.minecraft.class_3268.method_14405(class_3268.java:89) ~[intermediary-1.15.2.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:420) [intermediary-1.15.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:166) [intermediary-1.15.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.8+build.185.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.8+build.185.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.8+build.185.jar:?]
[15:19:00] [main/INFO]: Narrator library for x64 successfully loaded
[15:19:01] [main/INFO]: Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Networking Block Entity (v0), Fabric Key Bindings (v0), VexView, Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Biomes (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric API Base, Fabric Rendering (v0), Fabric Rendering (v1), Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Rendering Fluids (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Hwyla, Fabric BlockRenderLayer Registration (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), VoxelMap, Fabric Events Lifecycle (v0), Fabric Loot Tables (v1), Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0), Fabric Networking (v0)
[15:19:14] [main/WARN]: Missing sound for event: minecraft:ambient.cave
[15:19:14] [main/WARN]: Missing sound for event: minecraft:ambient.underwater.enter
[15:19:14] [main/WARN]: Missing sound for event: minecraft:ambient.underwater.exit
[15:19:14] [main/WARN]: Missing sound for event: minecraft:ambient.underwater.loop
[15:19:14] [main/WARN]: Missing sound for event: minecraft:ambient.underwater.loop.additions
[15:19:14] [main/WARN]: Missing sound for event: minecraft:ambient.underwater.loop.additions.rare
[15:19:14] [main/WARN]: Missing sound for event: minecraft:ambient.underwater.loop.additions.ultra_rare
[15:19:14] [main/WARN]: Missing sound for event: minecraft:block.anvil.break
.......

**Comment by Eerobrine** [comment]
哥哥能分享下jmccc-yggdrasil-authenticator 2.5-SNAPSHOT嘛，pom一直报错，编译不出来。
